### ISSUE TITLE
Cannot find module 'node:path'

### ISSUE THREAD

**Issue by SeriousM** [Rbillon59/hass-n8n#10]
Hi! Thank you very much for publishing this addon, I was about to build it myself as n8n is just such an incredible useful thing :)

But sadly the addon dies during startup.

HA Info: 
 Home Assistant 2022.12.1
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221208.0 - latest
Current hass n8n addon version: 0.0.4

```log
    Error: Cannot find module 'node:path'
    Require stack:
    - /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/DirectoryLoad
    er.js
    - /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/index.js
    - /usr/local/lib/node_modules/n8n/dist/commands/start.js
    - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/plugin.js
    - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/config.js
    - /usr/local/lib/node_modules/n8n/node_modules/@oclif/config/lib/index.js
    - 
    /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/command.js
    - /usr/local/lib/node_modules/n8n/node_modules/@oclif/command/lib/index.js
    - /usr/local/lib/node_modules/n8n/bin/n8n
    Code: MODULE_NOT_FOUND
```

That's all of information I found.
Btw, why do you build the n8n image yourself? There is an official image already: `n8nio/n8n`

**Comment by Rbillon59** [comment]
Hey, 

Thank you for raising an issue, I'll check it out this week.

> Btw, why do you build the n8n image yourself? There is an official image already: n8nio/n8n

Probably because when I started using this addon, this image simply did not exist :) 

Thank you for pointing this out, I will probably use it and avoid your home assistant to deal with this time and resource consuming build

**Comment by Rbillon59** [comment]
Can you please check again with the new version ?

**Comment by SeriousM** [comment]
yep, looks good. thank you!
