### ISSUE TITLE
Call n8n like a HASS Assistant

### ISSUE THREAD

**Issue by denisjoshua** [Rbillon59/hass-n8n#136]
Hi there, and sorry for the strange question. 
I use n8n and I like so much, so I wonder if I can make the Assistant in Home Assistant that can call the n8n workflow. 

Actually we can make an Ollama local server and then set it on Ollama add-on service in Home Assistant, 
in order to set it then in Assist. 
So it's possible to set n8n server in the Home Assistant Assist please ? 

Thanks in advance 
Denis

**Comment by Rbillon59** [comment]
Yes, there are a few solutions.

For example, I believe, you can create home assistant scripts that will call the n8n webhook URL, and then expose those scripts in the assistant to action any n8n workflows

**Comment by denisjoshua** [comment]
I just work on n8n workflow that simulate OpenAI API and in Home Assistant I use the [Home LLM](https://github.com/acon96/home-llm) add-on.

I'm in the middle of flow for now... but it's work (at last the input it arrive :-) 

Thanks for the answer.

**Comment by Rbillon59** [comment]
Perfect !
