### ISSUE TITLE
how to find it

### ISSUE THREAD

**Issue by lublak** [Rbillon59/hass-n8n#25]
Just a stupid question.
How to find it?
Is there a repo url?

![grafik](https://user-images.githubusercontent.com/44057030/219817449-846e338d-35b8-48b9-aa36-c8608e517e83.png)

Example:
https://github.com/Rbillon59/hass-n8n

I can just add this url as a repo: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
And it shows me the zigbee2mqtt addons

**Comment by Rbillon59** [comment]
Hi @lublak !

Actually, I've created multiple addons, so I created a repository to add in home-assistant : https://github.com/Rbillon59/home-assistant-addons

**Comment by Rbillon59** [comment]
I've updated the readme with the link to the addon repository

**Comment by lublak** [comment]
@Rbillon59
That's fine too :P
The main thing is that you can add it somehow.
Thank you!
