### ISSUE TITLE
Specify Folder Path

### ISSUE THREAD

**Issue by BenJamesAndo** [Rbillon59/hass-n8n#34]
Hello. I'm trying to figure out what folders and files n8n is able to see. It seems to be the /data folder, yet if I put something else in that folder n8n can't see it. I'm using the execute command to list files and folders and all it can see is options.json
I created a n8n folder in data to see if that would help but it didn't.

Is there a way to specify what folders n8n could see? Ideally I'd like it to see the Home Assistants /backup folder and use a file trigger within n8n.

**Comment by Rbillon59** [comment]
Hello, I've added

**Comment by Rbillon59** [comment]
![image](https://user-images.githubusercontent.com/17565349/235606950-e4bc67c9-1943-4661-b8a3-62c04e2f6fbf.png)

![image](https://user-images.githubusercontent.com/17565349/235607074-5795bf42-cb82-4978-b87d-194bfdb47c57.png)


All set ! Feel free to update and enjoy.

Have a nice day !

**Comment by BenJamesAndo** [comment]
Thanks so much!
