### ISSUE TITLE
Increase Max Payload

### ISSUE THREAD

**Issue by BenJamesAndo** [Rbillon59/hass-n8n#37]
n8n by default seems to only allow files of 16MB or smaller to be processed. As per the recent update where the /backup folder is recognised I'd like to be able to process some files that are larger than 16MB, as are most backup files.

Is it possible to add an addon configuration to increase the max size? e.g. 2048MB. The variable is `N8N_PAYLOAD_SIZE_MAX` as per [n8n environment variables reference guide](https://docs.n8n.io/hosting/environment-variables/environment-variables/#endpoints)

**Comment by Rbillon59** [comment]
Hi @BenJamesAndo !

What is your use case here ? I tried to upload a backup file (190MB) to a FTP using n8n and it was successful. 
![image](https://github.com/Rbillon59/hass-n8n/assets/17565349/8477ca68-59e0-4b66-b0aa-1f44301657af)


Also, keep in mind, if working with binary data, they will be loaded in JVM, so you need as more heap size as the file size

**Comment by BenJamesAndo** [comment]
Hi @Rbillon59 I probably need to learn n8n better. Because I can't figure out how to upload to FTP without first using a 'Read Binary Files' node. If I do it straight from a local file trigger to FTP it uploads a file with the same name, but it's much smaller. I think the file it creates is just a file with the 'path' as the contents, rather than the actual contents of the file.

![image](https://github.com/Rbillon59/hass-n8n/assets/44917135/b422fef2-5a99-4de9-8c98-aa708a178134)
![image](https://github.com/Rbillon59/hass-n8n/assets/44917135/a7f6a31f-19cd-4863-8fb3-8163dabcda89)

**Comment by BenJamesAndo** [comment]
Hey that sounds like a cool idea! Because I was actually thinking having control over the `WEBHOOK_TUNNEL_URL` & `EXECUTIONS_PROCESS` env variable would be good. Would actually be really nice if all HA addons allowed for complete control over env variables. Hopefully you figure out a way to pull it off.

**Comment by Rbillon59** [comment]
Could you please update the addon and try what you want ? Let me know if you face any issue.

Thanks

**Comment by BenJamesAndo** [comment]
I've tested a bunch of variables and they work great. Thanks! It's a very nice implementation of the feature.

**Comment by Rbillon59** [comment]
Awesome ! Closing the issue, enjoy !
